queries:
 - query_name : query1
   catalog : dengDIDataStore-test
   schema : precipitation
   query : StationName = 'KANDY'

 - query_name : query2
   catalog : dengDIDataStore-test
   schema : weatherstations
   query : StationName = 'KANDY'

 - query_name : query3
   catalog : dengDIDataStore-test
   schema : moh
   query : MohName = 'Panadura'

# - query_name : query2
#   catalog : dengDIDataStore-test
#   schema: precipitation
#   query: bbox(geom,79.84,6.7761,80.2228,6.9861) AND dtg DURING 2013-01-01T00:00:00.000Z/2013-01-31T00:00:00.000Z
#
# - query_name : query3
#   catalog : dengDIDataStore-test
#   schema: precipitation
#   query: StationName = 'Homagama' AND dtg DURING 2013-01-01T00:00:00.000Z/2013-01-31T00:00:00.000Z