hbase.zookeepers: "localhost"

hbase.catalog: "weatherdata"

simple_feature_types:
  - feature_name: "precipitation"
    attributes:
      -  attribute: "StationID:String:index=true"
         attributeName: "StationID"
         attributeType: "String"
      -  attribute: "StationName:String"
         attributeName: "StationName"
         attributeType: "String"
      -  attribute: "Latitude:String"
         attributeName: "Latitude"
         attributeType: "String"
      -  attribute: "Longitude:String"
         attributeName: "Longitude"
         attributeType: "String"
      -  attribute: "dtg:Date"
         attributeName: "dtg"
         attributeType: "Date"
      -  attribute: "ObservedValue:String"
         attributeName: "ObservedValue"
         attributeType: "String"
      -  attribute: "*geom:Point:srid=4326"
         attributeName: "geom"
         attributeType: "Point"

    configurations:
        GeomFormat: "Point"
        DateTimeFormat: "yyyyMMdd"
        FeatureID: "StationID"
