hbase.zoookeepers: "localhost"

hbase.catalog: "weatherdata"

feature_name: "weather-data-precipitation"

attributes:
  -  attribute: "StationID:String:index=true"
     attributeName: "StationID"
     attributeType: "String"
  -  attribute: "StationName:String"
     attributeName: "StationName"
     attributeType: "String"
  -  attribute: "Latitude:String"
     attributeName: "Latitude"
     attributeType: "String"
  -  attribute: "Longitude:String"
     attributeName: "Longitude"
     attributeType: "String"
  -  attribute: "dtg:Date"
     attributeName: "dtg"
     attributeType: "Date"
  -  attribute: "ObservedValue:String"
     attributeName: "ObservedValue"
     attributeType: "String"
  -  attribute: "*geom:Point:srid=4326"
     attributeName: "geom"
     attributeType: "Point"

records:
   StationID: 0
   StationName: 1
   Latitude: 2
   Longitude: 3
   dtg: 4
   ObservedValue: 5
   Lat: 2
   Long: 3

configurations:
  DateTimeFormat: "yyyyMMdd"
  FeatureID: "StationID"

queries:
  - query_name: "query1"
    query_description: "Get all rainfall records of weather station in Mannar"
    query: "StationName = 'Mannar'"
  - query_name: "query2"
    query_description: "Get all records of weather stations within colombo district in January of 2013"
    query: "bbox(geom,79.84,6.7761,80.2228,6.9861) AND dtg DURING 2013-01-01T00:00:00.000Z/2013-01-31T00:00:00.000Z"
  - query_name: "query3"
    query_description: "get al records of Homagama weather station during the January of 2013"
    query: "StationName = 'Homagama' AND dtg DURING 2013-01-01T00:00:00.000Z/2013-01-31T00:00:00.000Z"

data_source: "weather-precipitation-data.csv"
#only csv files are supported.
