baseGranularity:
  spatial: "moh"
  temporal: "week"

mappings:
  - feature: "weatherstations"
    spatial:
      spatialGranularityType: "point"
      spatialGranularity: "weatherstations"
      spatialMapping: "nearest"
    temporal:
      temporalGranularityType: "duration"
      temporalGranularity: "day"
      temporalMapping: "mean"