simple_feature_types:
  - feature_name: "precipitation"
    source_type: "delimited-text"
    source_format: "CSV"
    feature_id: "md5(stringToBytes($0))"  #(we configure this)
    transformations:
      - attribute_name : "stationName"
        transformation: "$1"
      - attribute_name: "observedValue"
        transformation: "$2"
      - attribute_name: "date"
        transformation: "date($3)"
      - attribute_name: "spatialGranule"
        transformation: "$1"
      - attribute_name: "temporalGranule"
        transformation: "date($3)"
    data_sources:
      - "Data/precipitation/daily_weather_srilanka-01_1_2013.csv"
      - "Data/precipitation/daily_weather_srilanka-01_2_2013.csv"

  - feature_name: "dengue_cases"
    source_type: "delimited-text"
    source_format: "CSV"
    feature_id: "md5(stringToBytes($0))"
    transformations:
      - attribute_name : "mohArea"
        transformation: "$1"
      - attribute_name: "caseCount"
        transformation: "$2"
      - attribute_name: "date"
        transformation: "date($3)"
      - attribute_name: "spatialGranule"
        transformation: "$1"
      - attribute_name: "temporalGranule"
        transformation: "date($3)"
    data_sources:
      - "Data/denguecases/dengueCases2013.csv"

granualrity_feature_types:
  - feature_name: "weatherstation"
    granularity_type: "spatial"
    source_type: "delimited-text"
    source_format: "CSV"
    feature_id: "md5(stringToBytes($0))"
    transformations:
      - attribute_name: "stationName"
        transformation: "$1"
      - attribute_name: "latitude"
        transformation: "$2"
      - attribute_name: "longitude"
        transformation: "$3"
      - attribute_name: "geom"
        source: "in-source"
        transformation: "point($longitude, $latitude)"
    geom_configurations:
      geom_format: "Point"
      data_source: "csv"
      feature_id: "stationName"
    data_source: "Data/WeatherStations/WeatherStations.csv"

  - feature_name: "moh"
      granularity_type: "spatial"
      source_type: "shp"
      source_format:
      feature_id: "$0"
      transformations:
        - attribute_name: "StationName"
          transformation: "$1"
        - attribute_name: "latitude"
          transformation: "$2"
        - attribute_name: "longitude"
          transformation: "$3"
        - attribute_name: "geom"
          transformation: "shp($4)"
      geom_configurations:
        geom_format: "Point"
        data_source: "csv"
        feature_id: "StationName"
      data_source: "Data/ShapeFiles/SL_MOH.shp"
