baseGranularity:
  spatial: "moh"
  temporal: "week"

mappings:
  - featureTypeName: "weatherstations"
    spatial:
      spatialGranularity: "weatherstations"
      spatialMapping: "nearest"
    temporal:
      temporalGranularity: "day"
      temporalMapping: "mean"
    customAttributes:
      neighbors: 3
      maxDistance: 10000