simple_feature_types:
  - feature_name: "precipitation"
    records:
      StationName: 0
      ObservedValue: 1
      dtg: 2
      Latitude: 3
      Longitude: 4
      Lat: 3
      Long: 4

    configurations:
      DateTimeFormat: "yyyyMMdd"
      FeatureID: "StationName"

    data_source: "Data/percipitation/daily_weather_srilanka-01_1_2013.csv"


    shp_file:
      FeatureID: "MOH_N"

  - feature_name: "weatherstations"
    records:
      StationName: 0
      Latitude: 1
      Longitude: 2
      Lat: 1
      Long: 2

    configurations:
      GeomFormat: "Point"
      FeatureID: "StationName"

    data_source: "Data/WeatherStations/WeatherStations.csv"

    shp_file:
      FeatureID: "MOH_N"

  - feature_name: "moh"
    records:
      MohName: 0
      Latitude: 1
      Longitude: 2
      Lat: 1
      Long: 2

    configurations:
      GeomFormat: "Polygon"
      FeatureID: "MohName"

    data_source: "Data/MOH/moh.csv"

    shp_file:
      Source: "Data/ShapeFiles/SL_MOH.shp"
      FeatureID: "MOH_N"

